name              'xinetd'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs/Configures xinetd'
version           '2.1.1'
source_url        'https://github.com/sous-chefs/xinetd'
issues_url        'https://github.com/sous-chefs/xinetd/issues'
chef_version      '>= 15.3'

supports 'centos'
supports 'debian'
supports 'redhat'
supports 'ubuntu'
